Декоративные элементы главной страницы
htmlacademy-adaptive/1775757-cat-energy-23 pull request #7
Opened 2021-08-08 22:39 UTC by Lobanov88

2021-08-08 22:45 UTC, Lobanov88 commented
Сделал все что мог.

Несколько вопросов, которые совсем не понимаю.

1) Попробовал добавить два изображения в каталоге через picture
Если у lmg есть атрибуты width и height то не работает(
Если убрать у img width и height, то работает


2) зеленые линии в форме на заголовках пробовал по-разному, но пока так и не нашел способа заставить и правильно появиться

3) иконки в input с телефоном и почтой не осилил разукрасить

4) слайдер что-то пока прям не пойму с какой стороны подступиться

Не знаю, может, эти вопросы в качестве консультации как-то

2021-08-09 03:43 UTC, VAnastasia commented
> Сделал все что мог.
> 
> Несколько вопросов, которые совсем не понимаю.
> 
> 1. Попробовал добавить два изображения в каталоге через picture
>    Если у lmg есть атрибуты width и height то не работает(
>    Если убрать у img width и height, то работает
> 2. зеленые линии в форме на заголовках пробовал по-разному, но пока так и не нашел способа заставить и правильно появиться
> 3. иконки в input с телефоном и почтой не осилил разукрасить
> 4. слайдер что-то пока прям не пойму с какой стороны подступиться
> 
> Не знаю, может, эти вопросы в качестве консультации как-то

1. width и height убрать (только в каталоге)
2. Если обернуть в container не всю форму, а содержимое каждого fieldset, тогда сами fieldset растянутся на всю ширину и можно будет сделать зеленые линии псевдоэлементами fieldset
3. Чтобы менять цвет иконкам, их надо добавить в разметку как svg, добавить обертку input-ам, в которой будет input и svg, и спозиционировать svg через position: absolute
4. Слайдер - это одна картинка поверх другой, у верхней меняется ширина. Проблема тут может возникнуть с серо-белым фоном
Если нужна будет консультация, оставляй заявку, время согласуем

2021-08-09 14:39 UTC, Lobanov88 commented
1) img в picture без атрибутов width и height в каталоге - ОК, все норм

2) Зеленые линии на заголовках в форме. Переместил контейнеры. Но опять не то. В пикселях ширина - либо слишком короткая, либо появляется прокрутка горизонтальная. Поставил чтобы начиналось с 0 и ширина 100%.
В мобильной версии слева вообще не должно быть. А в планшетной или декстопной там дальше от заголовка они.

3) да, так ок, просто изначально хотел backgorund-image использовать

со слайдером пока не очень, но там вроде время позволяет

2021-08-11 03:38 UTC, VAnastasia requested changes

2021-08-11 03:38 UTC, VAnastasia commented on source/index.html
> +              <p class="true-story__toggle-text">Было</p>
Было/стало - надо сделать кнопками или ссылками, это интерактивные элементы, и у них есть состояния по стайлгайду

2021-08-11 06:45 UTC, Lobanov88 commented on source/index.html
> +              <p class="true-story__toggle-text">Было</p>
Да, косяк, проскочил. Было/Стало сделал. Там все просто

![Снимок экрана 2021-08-11 в 9 34 20](https://user-images.githubusercontent.com/84290268/128981933-cbf74cd6-9ce0-48ea-b2a4-4eb2f846d91e.png)

а как быть с кружком, он тоже кнопка?

2021-08-11 09:54 UTC, VAnastasia commented on source/index.html
> +              <p class="true-story__toggle-text">Было</p>
да

2021-08-11 12:16 UTC, merged